# Habilitar o console do banco de dados H2 para testes
spring.h2.console.enabled=true

# Expor os endpoints do Actuator (health, info e metrics)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always